config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:new, :create]
  resources :lists, only: [:index, :show] do
    resources :bookmarks, only: [:create, :new]
  end
  resources :bookmarks, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :list, presence: true
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true
  validates :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @movies = Movie.all
    @list.save
    redirect_to lists_path
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<div>
  <%= link_to "Back to lists", list_path(@list) %>
</div>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Add to list", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>List of Lists</h1>

<p>Please choose a list or create a new one</p>
<%= link_to "Create a list", new_list_path %>

<div id="lists">
  <% @lists.each do |list| %>
    <h2><%=  list.name %></h2>
    <p>
      <%= link_to "Show this list", list_path(list.id) %>
    </p>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

<%= simple_form_for(@list) do |f| %>

<div class="form-inputs">
    <%= f.input :name %>
</div>

 <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/show.html.erb
<h1> <%= @list.name %> </h1>

<button> <%= link_to "Add a movie in this list", new_list_bookmark_path(@list.id) %> </button>

<button> <%= link_to "Back to all lists", lists_path %> </button>

<ul>
  <% @list.movies.each do |movie|  %>
    <li> <%= movie.title %> </li>
  <% end %>
</ul>